### PR TITLE
[15.0][connector_jira][connector_jira_servicedesk] computes

### PR DESCRIPTION
**Pull request by leemannd**
There are computes that are not assigning a value at each time

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by gurneyalex** [comment]
@leemannd what is the status of this PR ? I don't see it on our odoo but the PR is quite old.

**Comment by leemannd** [comment]
Hello, @gurneyalex it is stalled for the moment

**Comment by leemannd** [comment]
Closing the PR as it is old and I don't have time to work on

**Pull request closed without merging**
