### PR TITLE
[12.0][FIX] connector_jira: issues can be moved between projects

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@guewen @simahawk please review this one

**Comment by guewen** [comment]
Are you sure? IIRC when testing, when moving a task, was creating a new one and deleting the previous one.

**Comment by guewen** [comment]
(∩｀-´)⊃━☆ﾟ.*･｡ﾟ

/ocabot merge

**Comment by alexey-pelykh** [comment]
> Are you sure? IIRC when testing, when moving a task, was creating a new one and deleting the previous one.

I'm 100% sure that it does not recreate it, linkage is not broken

**Comment by alexey-pelykh** [comment]
And as result we have AAL being linked to (new_project, task) while task is linked to old_project

**Pull request merged**
