### PR TITLE
[12.0][MIG] connector_jira

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@guewen @simahawk @grindtildeath this is a WIP, yet since I'm very new to this module, your help would be much appreciated

**Comment by alexey-pelykh** [comment]
I doubt this screen looks ok:
image

**Comment by alexey-pelykh** [comment]
All dependencies have been merged, so this one is super-ready to be reviewed and tested

**Review by simahawk — APPROVED** [review]
eyeball code review only on last commit for v12: seems good

**Comment by alexey-pelykh** [comment]
image
~here's an issue~ this issue is related to dependency, nothing to do here

**Comment by alexey-pelykh** [comment]
image
~and another unclear behavior related to `report_user_sync` probably being empty~

image

*fixed*

**Comment by alexey-pelykh** [comment]
```
        _logger.info('!!!! _run_background_from_date %s' % model)
        # self.env[model].with_delay(priority=9).run_batch_timestamp(
        #     self, timestamp
        # )
        self.env[model].run_batch_timestamp(
            self, timestamp
        )
```
Seems that `with_delay` delays indefinitely or something

**Comment by alexey-pelykh** [comment]
`"POST /connector_jira/webhooks/issue?user_id=alexey.pelykh&user_key=admin HTTP/1.0"` also didn't do a thing? But it also uses `with_delay`

**Comment by alexey-pelykh** [comment]
~`WARNING ? odoo.addons.queue_job.jobrunner.channels: unknown channel root.connector_jira.import, using root channel for job b3db1ffa-dd45-4162-b850-30ff889ba64a` not sure what that means~ added to installation instruction

**Review by guewen — APPROVED** [review]
Looks good to me

**Comment by alexey-pelykh** [comment]
Good to merge I guess?

**Pull request merged**
