### PR TITLE
[MIG][13.0] connector jira

### PR DESCRIPTION
**Pull request by i-vyshnevska**

### CODE REVIEW

**Comment by i-vyshnevska** [comment]
@simahawk @guewen reviews are welcomed

**Review by gurneyalex — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Please include f1c7f12826e10d02f7d65802ee182b5f1e7a1837 if possible

**Comment by leemannd** [comment]
PR with fast-track removed

**Review by leemannd — APPROVED** [review]
Tested and works smoothly

**Pull request merged**
