### PR TITLE
[13.0][MIG] connector_jira_tempo

### PR DESCRIPTION
**Pull request by leemannd**

### CODE REVIEW

**Comment by grindtildeath** [comment]
To rebase after #60 is merged

**Comment by leemannd** [comment]
@simahawk Rebased. If the PR is ok for you, I will just rebase and remove the fixup from @grindtildeath

**Review by simahawk — APPROVED** [review]
LG. Squash your last commit as well

**Comment by leemannd** [comment]
@simahawk Update. Thanks

**Review by guewen — APPROVED** [review]

**Pull request merged**
