### PR TITLE
[11.0] connector_jira: Add epic link on epic

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Will there be a v12 port of it? :)

**Comment by gurneyalex** [comment]
@alexey-pelykh we have funding for a 13.0 migration, which is in progress. No migration to 12.0 planned from us at the moment.

**Comment by alexey-pelykh** [comment]
@gurneyalex https://github.com/OCA/connector-jira/pull/52 it's just a cherry-pick in the end. But I find test a bit odd though, just noticed

**Pull request merged**
