### PR TITLE
[11.0][IMP] multi_step_wizard: Go Back

### PR DESCRIPTION
**Pull request by jarroyomorales**
Allows to go to the previous step in wizards

### CODE REVIEW

**Comment by jarroyomorales** [comment]
@guewen @alexey-pelykh Any help with the Travis error? `curl: (6) Could not resolve host: cli-assets.heroku.com`

**Comment by alexey-pelykh** [comment]
@jarroyomorales just a glitch in Travis, restarting the job would do the trick

**Comment by jarroyomorales** [comment]
@alexey-pelykh Thank you!

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Looks good to me, @jarroyomorales do you plan to make a forward-port?

**Review by simahawk — APPROVED** [review]
LG

**Comment by jarroyomorales** [comment]
@alexey-pelykh Sure, I can do it

**Comment by alexey-pelykh** [comment]
v12 is in other repo, just FYI

**Comment by alexey-pelykh** [comment]
@jarroyomorales https://github.com/OCA/server-ux/tree/12.0/multi_step_wizard

**Comment by Tonow-c2c** [comment]
Hello @jarroyomorales 

I have this issue :

```
Error:
Odoo Server ErrorTraceback (most recent call last):
  File "/odoo/src/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/src/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/src/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/src/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/src/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/src/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/src/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/src/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo/src/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/src/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/src/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/external-src/connector-jira/multi_step_wizard/models/multi_step_wizard.py", line 61, in open_previous
    'No method defined for state %s' % (self.state,)
NotImplementedError: No method defined for state final
```

Should you add all "state_previous*" method https://github.com/OCA/connector-jira/blob/d80aac0c708f90b4453426e25458555bdc6f9141/multi_step_wizard/models/multi_step_wizard.py#L58
* final
* link_organizations

like "state_exit*" https://github.com/OCA/connector-jira/blob/7fcff785b26bee8596184a21588e849aabab371e/connector_jira/models/project_project/project_link_jira.py#L97

**Comment by jarroyomorales** [comment]
@Tonow-c2c Hi! Sorry for replying so late, I didnt see the comment. You have to inherit from this abstract model and then define the funcionts state_previous_ for each state but the start one!

**Pull request merged**
